"""initial schema

Revision ID: 2c077d327024
Revises:
Create Date: 2026-09-12 03:14:31.783003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2c077d327024"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("schema_version", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("base_revision", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("size_bytes >= 0", name="ck_artifacts_size_non_negative"),
        sa.PrimaryKeyConstraint("artifact_id"),
        sa.UniqueConstraint("object_key"),
        sa.UniqueConstraint(
            "tenant_id", "run_id", "kind", "sha256", name="uq_artifacts_content_identity"
        ),
    )
    op.create_index(op.f("ix_artifacts_run_id"), "artifacts", ["run_id"], unique=False)
    op.create_index(op.f("ix_artifacts_tenant_id"), "artifacts", ["tenant_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("actor_type", sa.String(), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_audit_events_run_id"), "audit_events", ["run_id"], unique=False)
    op.create_index(
        "ix_audit_events_run_id_event_type", "audit_events", ["run_id", "event_type"], unique=False
    )
    op.create_index(op.f("ix_audit_events_tenant_id"), "audit_events", ["tenant_id"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("request_sha256", sa.String(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("request_artifact_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status in ('PENDING', 'STARTED', 'FAILED')", name="ck_idempotency_key_status"
        ),
        sa.PrimaryKeyConstraint("tenant_id", "key"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "model_calls",
        sa.Column("model_call_id", sa.UUID(), nullable=False),
        sa.Column("logical_call_key", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("work_item_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reserved_usd", sa.Numeric(), nullable=False),
        sa.Column("actual_usd", sa.Numeric(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("response_artifact_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status in ('RESERVED', 'SETTLED', 'RELEASED', 'UNKNOWN')", name="ck_model_calls_status"
        ),
        sa.PrimaryKeyConstraint("model_call_id"),
        sa.UniqueConstraint("logical_call_key"),
    )
    op.create_index(op.f("ix_model_calls_run_id"), "model_calls", ["run_id"], unique=False)
    op.create_index(op.f("ix_model_calls_tenant_id"), "model_calls", ["tenant_id"], unique=False)
    op.create_table(
        "policy_decisions",
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("work_item_id", sa.UUID(), nullable=True),
        sa.Column("policy_version", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("allow", sa.Boolean(), nullable=False),
        sa.Column("reason_code", sa.String(), nullable=False),
        sa.Column("normalized_resource", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_index(
        op.f("ix_policy_decisions_run_id"), "policy_decisions", ["run_id"], unique=False
    )
    op.create_table(
        "run_budgets",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("max_cost_usd", sa.Numeric(), nullable=False),
        sa.Column("max_model_calls", sa.Integer(), nullable=False),
        sa.Column("spent_usd", sa.Numeric(), nullable=False),
        sa.Column("reserved_usd", sa.Numeric(), nullable=False),
        sa.Column("settled_calls", sa.Integer(), nullable=False),
        sa.Column("reserved_calls", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("max_cost_usd > 0", name="ck_run_budgets_max_cost_positive"),
        sa.CheckConstraint("max_model_calls > 0", name="ck_run_budgets_max_calls_positive"),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(op.f("ix_run_budgets_tenant_id"), "run_budgets", ["tenant_id"], unique=False)
    op.create_table(
        "run_projections",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("base_revision", sa.String(), nullable=True),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("model_calls", sa.Integer(), nullable=False),
        sa.Column("spent_usd", sa.Numeric(), nullable=False),
        sa.Column("reserved_usd", sa.Numeric(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("run_id"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_index(op.f("ix_run_projections_status"), "run_projections", ["status"], unique=False)
    op.create_index(
        op.f("ix_run_projections_tenant_id"), "run_projections", ["tenant_id"], unique=False
    )
    op.create_table(
        "work_item_projections",
        sa.Column("work_item_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("input_revision", sa.String(), nullable=True),
        sa.Column("output_artifact_id", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run_projections.run_id"],
        ),
        sa.PrimaryKeyConstraint("work_item_id"),
    )
    op.create_index(
        op.f("ix_work_item_projections_run_id"), "work_item_projections", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_work_item_projections_status"), "work_item_projections", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_item_projections_status"), table_name="work_item_projections")
    op.drop_index(op.f("ix_work_item_projections_run_id"), table_name="work_item_projections")
    op.drop_table("work_item_projections")
    op.drop_index(op.f("ix_run_projections_tenant_id"), table_name="run_projections")
    op.drop_index(op.f("ix_run_projections_status"), table_name="run_projections")
    op.drop_table("run_projections")
    op.drop_index(op.f("ix_run_budgets_tenant_id"), table_name="run_budgets")
    op.drop_table("run_budgets")
    op.drop_index(op.f("ix_policy_decisions_run_id"), table_name="policy_decisions")
    op.drop_table("policy_decisions")
    op.drop_index(op.f("ix_model_calls_tenant_id"), table_name="model_calls")
    op.drop_index(op.f("ix_model_calls_run_id"), table_name="model_calls")
    op.drop_table("model_calls")
    op.drop_table("idempotency_keys")
    op.drop_index(op.f("ix_audit_events_tenant_id"), table_name="audit_events")
    op.drop_index("ix_audit_events_run_id_event_type", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_run_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_artifacts_tenant_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_run_id"), table_name="artifacts")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
